### ISSUE TITLE
Setup Receipts issue

### ISSUE THREAD

**Issue by dwillitzer** [mailmate/receipts.mmbundle#1]
When the receipts app is installed from Setapp the application name is `de.holtwick.mac.receipts-setapp`, resulting the script to fail.

I have tried using a symbolic and hardlink from `com.apperdeck.mac.Receipts` to `de.holtwick.mac.receipts-setapp`, but does not fix this. 

🩹Temp solution is to edit the bash script ‘add’ with the mentioned setapp name.

Any thoughts?

**Comment by michaeltarleton** [comment]
I just ran into the same problem... maybe we should create a PR for checking for both...

**Comment by simonCGN** [comment]
Still not solved today. I still get the error message that Apple Mail script cannot get the ID for de.holtwick.mac.receipts-setapp

**Comment by simonCGN** [comment]
> Still not solved today. I still get the error message that Apple Mail script cannot get the ID for de.holtwick.mac.receipts-setapp

Still getting the same problem. Any chances that gets fixed, please? I would very much appreciate that automation to work.

**Comment by freron** [comment]
Sorry about the delay! I've merged the pull request from @michaeltarleton after reviewing it (but I didn't test it since I don't have Receipts installed). MailMate should automatically update the bundle within a few hours.

**Comment by dwillitzer** [comment]
Hey,

I wanted to confirm your latest release (Version 1.14 (5915) has 
resolved my issue!

Cheers,

Daniel Willitzer
(510) 685-5968 • ***@***.***

**Comment by freron** [comment]
Thanks for letting me know.
